#!/bin/sh
#$Id$

#
#	Copyright (C) 2005 Serg Oskin
#

ZM_VERSION=
ZM_CONFIG=/etc/zm.conf
UpgradeDir=/usr/lib/zm/upgrade

if [ -f $ZM_CONFIG ]; then
	. $ZM_CONFIG
else
	echo "ERROR: $ZM_CONFIG not found."
	exit 1
fi
for n in ZM_DB_SERVER ZM_DB_NAME ZM_DB_USER ZM_DB_PASS; do
	eval "val=\$$n"
	if [ "$val" = "" ]; then
		echo "ERROR($ZM_CONFIG): $n should exist and be not empty."
		exit 1
	fi
done

GetVer="select Value from Config where Name='ZM_DYN_CURR_VERSION'"
OLD_VERSION=`echo $GetVer | mysql -B -h $ZM_DB_SERVER -u $ZM_DB_USER -p$ZM_DB_PASS $ZM_DB_NAME | grep -v '^Value'`
[ "$ZM_VERSION" = "$OLD_VERSION" ] && exit 0

PWD=`pwd`
cd $UpgradeDir
sqls=`ls -1v zmalter-*.sql`
cd $PWD
if echo $sqls | grep "zmalter-$OLD_VERSION.sql" >/dev/null 2>&1; then
	sqls=`echo $sqls | sed -e "s/.*zmalter-$OLD_VERSION.sql/zmalter-$OLD_VERSION.sql/"`
	for v in $sqls; do
		cat $UpgradeDir/$v | mysql -h $ZM_DB_SERVER -u $ZM_DB_USER -p$ZM_DB_PASS $ZM_DB_NAME
	done
fi
SetVer="update Config set Value='$ZM_VERSION', DefaultValue='$ZM_VERSION' where Name='ZM_DYN_CURR_VERSION'"
echo $SetVer | mysql -B -h $ZM_DB_SERVER -u $ZM_DB_USER -p$ZM_DB_PASS $ZM_DB_NAME

if [ -x $UpgradeDir/zmalter-os ]; then
	$UpgradeDir/zmalter-os
fi
exit 0
