#!/bin/sh
#$Id$

#
#	Copyright (C) 2005 Serg Oskin
#

ZM_CONFIG=/etc/zm.conf
UpgradeDir=/usr/lib/zm/upgrade

if [ -f $ZM_CONFIG ]; then
	. $ZM_CONFIG
else
	echo "ERROR: $ZM_CONFIG not found."
	exit 1
fi
for n in ZM_DB_SERVER ZM_DB_NAME ZM_DB_USER ZM_DB_PASS; do
	eval "val=\$$n"
	if [ "$val" = "" ]; then
		echo "ERROR($ZM_CONFIG): $n should exist and be not empty."
		exit 1
	fi
done

GetVer="select Value from Config where Name='ZM_DYN_CURR_VERSION'"
ZM_VERSION=`echo $GetVer | mysql -B -h $ZM_DB_SERVER -u $ZM_DB_USER -p$ZM_DB_PASS $ZM_DB_NAME | grep -v '^Value'`

# Progress Bar
PE=`echo 'show columns from Monitors like "PostEvent"' \
	| mysql -h $ZM_DB_SERVER -u $ZM_DB_USER -p$ZM_DB_PASS $ZM_DB_NAME`
if ! echo $PE | grep 'PostEvent' >/dev/null 2>&1 ; then
	echo 'alter table Monitors add column PostEvent set("ProgressBar") NOT NULL default ""' \
		| mysql -h $ZM_DB_SERVER -u $ZM_DB_USER -p$ZM_DB_PASS $ZM_DB_NAME
fi
exit 0
